INSERT INTO employees (
  employee_code,
  first_name,
  last_name,
  email,
  phone,
  department,
  job_title,
  status,
  employment_type,
  manager_id,
  location,
  date_of_joining,
  date_of_exit,
  created_at,
  updated_at,
  notes
) VALUES (
  'EMP-1001',
  'John',
  'Doe',
  'john.doe@democorp.test',
  '9876543210',
  'Engineering',
  'Software Engineer',
  'ACTIVE',
  'FULL_TIME',
  1,
  'Bangalore',
  CURRENT_DATE,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP,
  'First sample employee.'
);

INSERT INTO employees (
  employee_code,
  first_name,
  last_name,
  email,
  phone,
  department,
  job_title,
  status,
  employment_type,
  manager_id,
  location,
  date_of_joining,
  date_of_exit,
  created_at,
  updated_at,
  notes
) VALUES (
  'EMP-1002',
  'Jane',
  'Smith',
  'jane.smith@democorp.test',
  '9988776655',
  'Human Resources',
  'HR Manager',
  'ACTIVE',
  'CONTRACT',
  2,
  'Delhi',
  CURRENT_DATE,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP,
  'Second sample employee.'
);